name: reanalysis 
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab=3.4.5
  - jupyterlab_widgets=1.1.1
  - widgetsnbextension=3.6.1
  - ipywidgets=7.7.1
  - pandas=1.4.3
  - gdal=3.5.1
  - xarray=2022.3.0
  - scipy=1.9.1
  - intake=0.6.6
  - intake-xarray=0.6.1
  - intake-stac=0.4.0
  - jupyter-server-proxy
  - h5py=3.7.0
  - tqdm=4.64.0
  - pip
  - pip:
      - intake_geopandas==0.4.0
