#!/bin/bash -l 
#SBATCH -t 02:00:00
#SBATCH -p batch
#SBATCH -N 1
#SBATCH -n 1 
#SBATCH -J Geopoints
#SBATCH --mem-per-cpu 128000

export PYTHONPATH=/projects/sequence_analysis/vol1/prediction_work/EDSReanalysis

python ./geopoints_simple_singleyear_reducedWaterlevels.py --year 2010 --filename 'fort.63.d0.no-unlim.T.rc.nc' --variable_name 'zeta' --geopointsfile '../testdata/NOAA_Stations_141.csv' --kmax=10 --alt_urlsource 'http://tds.renci.org/thredds/dodsC/Reanalysis/ADCIRC/ERA5/hsofs/%d'

# Execute the single year test code grabbing data from the LOCAL FS /projects/reanalysis/ADCIRC/ERA5/hsofs
# python ./geopoints_simple_singleyear_reducedWaterlevels.py --year 2010 --filename 'fort.63.d0.no-unlim.T.rc.nc' --variable_name 'zeta' --geopointsfile '../testdata/NOAA_Stations_141.csv' --kmax=10 --alt_urlsource '/projects/reanalysis/ADCIRC/ERA5/hsofs/%d'
#
#
#
