#!/bin/bash -l 

#SBATCH -t 02:00:00
#SBATCH -p batch
#SBATCH -N 1
#SBATCH -n 1 
#SBATCH -J Geopoints
#SBATCH --mem-per-cpu 64000

year=$1
keep_headers=$2

#POINTFILE="$EDSREANALYSIS/testdatalist_10000_points.csv"
POINTSFILE="$EDSREANALYSIS/testdata/hsofs_200grid_lonlat.csv"
POINTSFILE="$EDSREANALYSIS/testdata/NOAA_Stations_141.csv"

if [ "$keep_headers" == "1" ]; then
    python "$EDSREANALYSIS"/examples/geopoints_simple_singleyear_reducedWaterlevels.py --keep_headers --year "$year" --filename 'fort.63.d0.no-unlim.T.rc.nc' --variable_name 'zeta' --geopointsfile "$POINTSFILE" --kmax=10 --alt_urlsource 'http://tds.renci.org/thredds/dodsC/Reanalysis/ADCIRC/ERA5/hsofs/%d'
else
    python "$EDSREANALYSIS"/examples//geopoints_simple_singleyear_reducedWaterlevels.py --year "$year" --filename 'fort.63.d0.no-unlim.T.rc.nc' --variable_name 'zeta' --geopointsfile "$POINTSFILE" --kmax=10 --alt_urlsource 'http://tds.renci.org/thredds/dodsC/Reanalysis/ADCIRC/ERA5/hsofs/%d'
fi

